import { beforeEach, expect, it } from 'vitest';
import { applyD1Migrations } from 'cloudflare:test';
import { env } from 'cloudflare:workers';
import { SessionService } from '../src/auth/sessions';
import { createApp } from '../src/http/router';
import { activeQrCustomer } from '../src/qr/service';

beforeEach(async()=>{
 await env.DB.batch([env.DB.prepare('PRAGMA defer_foreign_keys=ON'),...['cursor_keys','spent_refresh_tokens','auth_rate_limits','access_sessions','disputes','sync_operations','entry_effective','ledger_entries','ledger_accounts','data_requests','refresh_sessions','shop_customers','customer_qr_ids','shops','users','d1_migrations'].map(t=>env.DB.prepare(`DROP TABLE IF EXISTS ${t}`))]);
 await applyD1Migrations(env.DB,env.MIGRATIONS);
});
it('D06 issues private random QR at registration, reads only own QR and rejects tampered rotation',async()=>{
 const sessions=new SessionService(env.DB),events:unknown[]=[],app=createApp({db:env.DB,sessions,logger:event=>events.push(event)});
 const c1=await sessions.exchange({sub:'c1',name:'SENSITIVE_NAME'},'customer','device');
 const c2=await sessions.exchange({sub:'c2'},'customer','device');
 const owner=await sessions.exchange({sub:'owner'},'owner','device');
 const rows=await env.DB.prepare('SELECT public_id FROM customer_qr_ids').all<{public_id:string}>();
 expect(rows.results).toHaveLength(2);
 expect(new Set(rows.results.map(r=>r.public_id)).size).toBe(2);
 for(const row of rows.results) expect(row.public_id).toMatch(/^[0-9a-f]{64}$/);
 const call=(token?:string,body?:unknown)=>app.fetch(new Request('https://test/v1/me/qr'+(body===undefined?'':'/rotate'),{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})}));
 expect((await call()).status).toBe(401);
 expect((await call(owner.accessToken)).status).toBe(403);
 expect((await call(owner.accessToken,{})).status).toBe(403);
 const first=(await (await call(c1.accessToken)).json() as {data:{version:number;publicQrId:string;payload:string}}).data;
 expect(first).toEqual({version:1,publicQrId:expect.stringMatching(/^[0-9a-f]{64}$/),payload:'udhaar://customer/v1/'+first.publicQrId});
 const second=(await (await call(c2.accessToken)).json() as {data:{publicQrId:string}}).data;
 expect(first.publicQrId).not.toBe(second.publicQrId);
 expect((await call(c1.accessToken,{customerUserId:c2.account.id})).status).toBe(400);
 const rotated=(await (await call(c1.accessToken,{})).json() as {data:{publicQrId:string}}).data;
 expect(rotated.publicQrId).not.toBe(first.publicQrId);
 await expect(activeQrCustomer(env.DB,first.publicQrId)).rejects.toMatchObject({code:'QR_REVOKED'});
 expect(await activeQrCustomer(env.DB,rotated.publicQrId)).toBe(c1.account.id);
 await expect(activeQrCustomer(env.DB,'f'.repeat(64))).rejects.toMatchObject({code:'QR_INVALID'});
 const logs=JSON.stringify(events);
 for(const secret of [first.publicQrId,rotated.publicQrId,c1.accessToken,'SENSITIVE_NAME']) expect(logs).not.toContain(secret);
 for(let i=0;i<2;i++)expect((await call(c1.accessToken,{})).status).toBe(200);
 expect((await call(c1.accessToken,{})).status).toBe(429);
 expect((await call(c2.accessToken,{})).status).toBe(200);
});
it('D06 rotation is atomic, preserves links, and fills QR for customers registered before D06',async()=>{
 const sessions=new SessionService(env.DB),app=createApp({db:env.DB,sessions,logger:()=>{}});
 const customer=await sessions.exchange({sub:'c'},'customer','device');
 const owner=await sessions.exchange({sub:'o'},'owner','device');
 await env.DB.prepare("INSERT INTO shops VALUES ('shop',?,'Shop','active',1,NULL)").bind(owner.account.id).run();
 await env.DB.prepare("INSERT INTO shop_customers VALUES ('link','shop',?,NULL,'active',1,NULL)").bind(customer.account.id).run();
 await env.DB.prepare('DELETE FROM customer_qr_ids WHERE customer_user_id=?').bind(customer.account.id).run();
 const get=()=>app.fetch(new Request('https://test/v1/me/qr',{headers:{Authorization:'Bearer '+customer.accessToken}}));
 expect((await get()).status).toBe(200);
 const old=await env.DB.prepare("SELECT public_id FROM customer_qr_ids WHERE customer_user_id=? AND status='active'").bind(customer.account.id).first('public_id');
 await env.DB.exec("CREATE TRIGGER test_rotation_failure BEFORE INSERT ON customer_qr_ids BEGIN SELECT RAISE(ABORT,'SYNTHETIC_FAILURE'); END");
 const rotate=()=>app.fetch(new Request('https://test/v1/me/qr/rotate',{method:'POST',headers:{Authorization:'Bearer '+customer.accessToken,'Content-Type':'application/json'},body:'{}'}));
 expect((await rotate()).status).toBe(500);
 expect(await env.DB.prepare("SELECT public_id FROM customer_qr_ids WHERE customer_user_id=? AND status='active'").bind(customer.account.id).first('public_id')).toBe(old);
 await env.DB.exec('DROP TRIGGER test_rotation_failure');
 const responses=await Promise.all([rotate(),rotate()]);
 expect(responses.map(r=>r.status)).toEqual([200,200]);
 expect(await env.DB.prepare("SELECT COUNT(*) count FROM customer_qr_ids WHERE status='active' AND customer_user_id=?").bind(customer.account.id).first('count')).toBe(1);
 expect(await env.DB.prepare("SELECT customer_user_id FROM shop_customers WHERE id='link'").first('customer_user_id')).toBe(customer.account.id);
 await env.DB.prepare('UPDATE users SET deleted_at_ms=2 WHERE id=?').bind(customer.account.id).run();
 expect((await get()).status).toBe(401);
});
