import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppStrings {
  const AppStrings(this.languageCode);
  final String languageCode;
  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings) ??
      const AppStrings('en');
  static const delegate = _StringsDelegate();
  static const supportedLocales = [Locale('en'), Locale('hi')];
  String text(String key, {Map<String, String> values = const {}}) {
    var result =
        (languageCode == 'hi' ? _hi : _en)[key] ??
        _en[key] ??
        _en['error.generic']!;
    for (final item in values.entries) {
      result = result.replaceAll('{${item.key}}', item.value);
    }
    return result;
  }

  String format(String english, {Map<String, String> values = const {}}) {
    var result = translate(english);
    for (final item in values.entries) {
      result = result.replaceAll('{${item.key}}', item.value);
    }
    return result;
  }

  String translate(String english) {
    final key = _reverse[english];
    return key == null ? english : text(key);
  }
}

class _StringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _StringsDelegate();
  @override
  bool isSupported(Locale locale) => ['en', 'hi'].contains(locale.languageCode);
  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture(AppStrings(locale.languageCode));
  @override
  bool shouldReload(_StringsDelegate old) => false;
}

String errorMessage(String key, {String languageCode = 'en'}) =>
    AppStrings(languageCode).text(key);
final Map<String, String> _reverse = {
  for (final e in _en.entries) e.value: e.key,
};
final Map<String, String> _en = {
  "ui0": "Cancel",
  "ui1": "Try again",
  "ui2": "Customer",
  "ui3": "Customers",
  "ui4": "Shop owner",
  "ui5": "Your shop",
  "ui6": "Set up your shop",
  "ui7": "Shop name",
  "ui8": "Shop nickname (optional)",
  "ui9": "Continue with Google",
  "ui10": "Sign out",
  "ui11": "Sign out?",
  "ui12": "Replace",
  "ui13": "Replace QR",
  "ui14": "Replace your QR?",
  "ui15": "Transaction history",
  "ui16": "View transaction history",
  "ui17": "View confirmed server history",
  "ui18": "View saved ledger",
  "ui19": "Customer ledger",
  "ui20": "Saved customer ledgers",
  "ui21": "Record credit",
  "ui22": "Record payment received",
  "ui23": "Amount (₹)",
  "ui24": "Amount received (₹)",
  "ui25": "Note (optional)",
  "ui26": "Due date (optional)",
  "ui27": "Cash",
  "ui28": "UPI",
  "ui29": "Back to customer",
  "ui30": "Back to ledger",
  "ui31": "Refresh balance",
  "ui32": "Refresh from server",
  "ui33": "Load more",
  "ui34": "Retry page",
  "ui35": "No transactions yet.",
  "ui36": "Please sign in",
  "ui37": "Please sign in to continue.",
  "ui38": "Please sign in and open this customer again.",
  "ui39": "Please sign in to open this ledger.",
  "ui40": "Could not open customer",
  "ui41": "Could not open your shop",
  "ui42": "Could not sign out. Please try again.",
  "ui43": "Scan customer QR",
  "ui44": "Scan another QR",
  "ui45": "Cancel and scan again",
  "ui46": "Show this to the shopkeeper",
  "ui47": "Checking your QR",
  "ui48": "Checking previous request",
  "ui49": "Finding customer",
  "ui50": "Opening customer",
  "ui51": "Opening shop",
  "ui52": "Loading server records",
  "ui53": "Loading local ledger",
  "ui54": "Loading credit form",
  "ui55": "Loading payment form",
  "ui56": "Open settings",
  "ui57": "Try camera again",
  "ui58": "Disputes",
  "ui59": "Raise dispute",
  "ui60": "Refresh disputes",
  "ui61": "Reason",
  "ui62": "Received by",
  "ui63": "Resolve with note below",
  "ui64": "Correct entry",
  "ui65": "Corrected amount (₹, zero allowed)",
  "ui66": "Confirm correction",
  "ui67": "Review correction",
  "ui68": "Edit correction",
  "ui69": "Edit credit",
  "ui70": "Edit payment",
  "ui71": "Edit amount and method",
  "ui72": "Review credit",
  "ui73": "Review payment",
  "ui74": "Check saved credit",
  "ui75": "Check saved payment",
  "ui76": "Check saved request",
  "ui77": "Credit acknowledged by server",
  "ui78": "Payment acknowledged by server",
  "ui79": "Credit saved · Pending",
  "ui80": "Payment saved · Pending",
  "ui81": "Payment rejected; no payment was recorded.",
  "ui82": "New phone and recovery",
  "ui83": "A simple record of customer credit.",
  "ui84": "Pending entries are only on this device and are not backed up to the cloud.",
  "ui85": "Pending entries are only on this device. They are not backed up to the cloud.",
  "ui86": "Server totals include Synced entries only. Pending entries are only on this device.",
  "ui87": "Offline · Saved account access on this device",
  "ui88":
      "Offline · Cached status · Read only. Refresh online for newer changes.",
  "ui89": "Cash/UPI is manually recorded by you. This app does not verify a bank transfer.",
  "ui90": "Cash/UPI payments are manually recorded by the owner; bank transfers are not verified.",
  "ui91": "The original entry is retained. A correction changes its effective amount.",
  "ui92": "Disputes do not change the balance. The owner records any financial correction separately.",
  "ui93": "This QR identifies your account. The shopkeeper confirms your identity and enters the amount. It is not a payment QR.",
  "ui94": "Scan the customer’s Udhaar Khata QR. Internet is needed to identify and add customers.",
  "ui95": "Allow camera access to scan a customer QR. You can change Camera permission in Android Settings.",
  "ui96": "Open Android Settings, then Apps, Udhaar Khata, Permissions to allow Camera.",
  "ui97": "Saved on this device. Balances may include Pending entries.",
  "ui98": "Showing the earlier server snapshot. The latest page could not be verified.",
  "ui99":
      "Original entry is retained. Review it before recording another entry.",
  "ui100": "Blocked by an earlier entry. Review the original entry first.",
  "ui101": "Refresh the customer ledger to see the latest balance.",
  "ui102": "Udhaar Khata",
  "ui103": "DD-MM-YYYY",
  "ui104": "Pending entries are only on this device. They are not backed up to the cloud. Customer views show only server-acknowledged entries.",
  "ui105": "Before changing phones, connect the old phone, retry sync, and check that no entries remain Pending or Needs attention. Do not recreate uncertain entries without checking the confirmed history.",
  "ui106": "Pending entries exist only on the phone where they were saved. If that phone is lost, damaged, or its app data is cleared before sync, the server cannot restore those entries.",
  "ui107": "Sign in with the same Google account on your new phone while connected to the internet. Open your ledgers to download server-acknowledged records.",
  "ui108": "Offline customer views show the last successful server snapshot. Newer owner changes may be missing until you reconnect and refresh.",
  "ui109": "This saved credit is not confirmed. It may already have reached the server. Check the same credit; do not enter it again.",
  "ui110": "This saved payment is not confirmed. It may already have reached the server. Check the same payment; do not enter it again.",
  "ui111": "The server balance changed. Review Pending entries before recording another entry.",
  "ui112": "Correction saved · Pending · Only on this device. It is not backed up to the cloud until synced.",
  "ui113": "A correction is Pending or Needs attention. The effective acknowledged amount excludes it.",
  "ui114": "Confirmed server entries. Payments are manually recorded by the owner; bank transfers are not verified.",
  "ui115": "The saved amount exceeds the balance or the ledger limit was reached. Review the current balance and correct the amount yourself.",
  "ui116": "Customer linked to your shop. Scanning and adding a customer records no credit or payment.",
  "ui117": "Internet is required. The old QR will stop working for new shop links. Your existing shop ledgers will remain.",
  "ui118": "Sign in again to check or replace your QR. This saved code has not been verified online.",
  "ui119": "Signed out on this phone. Cloud session revocation could not be confirmed.",
  "ui120": "Your customers will see this name beside their ledger. One shop per owner in this version. Internet is needed for setup.",
  "statement.title": "Statement and reminder",
  "statement.from": "From date (UTC)",
  "statement.to": "To date (UTC)",
  "statement.load": "Prepare preview",
  "statement.bounds": "Use a period of at most 366 days. Export supports at most 5,000 acknowledged entries.",
  "statement.period": "UTC posting period: {from} to {to}",
  "statement.sensitive": "Private financial information. Check the customer and choose the intended recipient in the share menu. Device Pending entries are excluded.",
  "statement.opening": "Opening balance: {amount}",
  "statement.closing": "Closing balance: {amount}",
  "statement.shareCsv": "Share CSV",
  "statement.sharePdf": "Share PDF",
  "reminder.share": "Share reviewed reminder",
  "reminder.label": "Editable reminder preview",
  "reminder.template": "Hello {customer}, our acknowledged records at {shop} show you owe {amount} as of {asOf}. Please review your ledger. Newer or device Pending entries may not be included. Thank you.",
  "owner.owes": "Customer owes you {amount}",
  "customer.owes": "You owe {shop} {amount}",
  "language": "Language",
  "help": "Help and recovery",
  "sync.pending": "Pending · only on this device",
  "sync.synced": "Synced · acknowledged by cloud",
  "sync.attention": "Needs attention",
  "error.generic": "Could not complete this action. Try again.",
  "ledger.cacheTooLarge": "This ledger is too large to save offline. View confirmed server history while online.",
  "ledger.localOverpayment": "Payment exceeds the locally known balance. Review the amount before saving.",
  "ledger.cacheRequired": "Open this customer online to verify and save their ledger before recording offline entries.",
  "api.cursorInvalid":
      "This snapshot has expired. Refresh to open the latest records.",
  "history.invalidResponse":
      "The server records could not be verified. Refresh and try again.",
  "history.failed":
      "Could not load the records. Check your connection and try again.",
  "api.capacityUnavailable":
      "The server cannot provide this total right now. Please try again later.",
  "payment.pending": "Check the saved payment before entering another credit or payment for this customer.",
  "payment.creditPending":
      "Check the saved credit before recording a payment for this customer.",
  "payment.savedInvalid": "The saved payment cannot be read. Keep this app data and contact support before entering it again.",
  "payment.invalid":
      "Use a positive amount up to ₹1,00,000 and select Cash or UPI.",
  "payment.balanceConflict": "This payment was rejected because it exceeds the current balance or ledger limit. Refresh the balance and review the amount.",
  "payment.failed": "Could not verify this payment. Check the same saved request; do not enter it again.",
  "credit.pending": "Check the saved credit before entering another credit for this customer.",
  "credit.savedInvalid": "The saved credit cannot be read. Keep this app data and contact support before entering this credit again.",
  "credit.invalid": "Use a positive amount up to ₹1,00,000, a note up to 500 characters, and a valid due date.",
  "credit.clockInvalid": "Check your phone date and time. The saved request is retained for review.",
  "credit.balanceLimit": "This credit exceeds the supported ledger balance. The saved request needs attention.",
  "credit.failed": "Could not verify this credit. Check the same saved request; do not enter it again.",
  "link.internetNeeded": "Internet is needed to identify and add this customer. Connect and try again.",
  "qr.invalid": "This is not a valid Udhaar Khata customer QR.",
  "qr.unsupported":
      "This QR version is not supported. Ask for a current customer QR.",
  "qr.revoked":
      "This QR is no longer active. Ask the customer for their current QR.",
  "api.notFound":
      "This shop or customer is no longer available to your account.",
  "api.idempotencyConflict": "This request conflicts with an earlier confirmation. Refresh the customer list before trying again.",
  "api.invalidResponse":
      "The response could not be verified. Check the same request again.",
  "link.pending":
      "Check your previous customer confirmation before scanning another QR.",
  "link.savedRequestInvalid": "Your saved confirmation could not be read. Contact support before trying to add another customer.",
  "link.nicknameInvalid": "Use a shop nickname of at most 120 characters.",
  "link.failed":
      "Could not confirm the customer. Check your connection and try again.",
  "auth.required": "Please sign in to continue.",
  "auth.forbidden": "You do not have access to this page.",
  "auth.cancelled": "Sign-in was cancelled. You can try again.",
  "auth.identityInvalid":
      "Google sign-in expired or could not be verified. Please sign in again.",
  "auth.roleConflict": "This Google account already has a different role. Choose its original role.",
  "api.rateLimited": "Too many attempts. Please wait and try again.",
  "api.networkError": "Could not connect. Check your connection and try again.",
  "qr.recoveryRequired": "Connect to the internet and refresh your QR. Its replacement could not be confirmed, so the saved QR is hidden.",
  "api.featureUnavailable":
      "This feature is not available yet. Please try again later.",
  "qr.rotationRecovered": "The replacement response could not be confirmed. The latest QR from the server is shown.",
  "api.validationError": "Check the fields and try again.",
  "api.internalError": "The server could not complete this request. Retry the same saved request.",
  "api.methodNotAllowed": "This action is not supported.",
  "api.invalidJson": "The saved request could not be read. Contact support.",
  "api.jsonRequired": "The request format is unsupported.",
  "api.payloadTooLarge": "This request is too large. Reduce the input.",
  "shop.closed": "This shop is closed.",
  "correction.failed":
      "Could not verify correction. Check the same saved request.",
  "dispute.failed": "Could not verify dispute. Refresh and try again.",
  "uiExtra0": "Original amount",
  "uiExtra1": "Effective acknowledged amount",
  "uiExtra2": "Correction",
  "uiExtra3": "Current acknowledged amount",
  "uiExtra4": "Original entry",
  "uiExtra5": "Corrected amount",
  "uiExtra6": "Outstanding",
  "uiExtra7": "Overdue",
  "uiExtra8": "Acknowledged server summary",
  "uiExtra9": "Created",
  "uiExtra10": "Resolution",
  "uiExtra11": "open",
  "uiExtra12": "resolved",
  "uiExtra13": "Entry",
  "uiExtra14": "Dispute reason",
  "uiExtra15": "Resolution note",
  "uiExtra16": "Settings and data controls",
  "uiExtra17": "Data requests",
  "uiExtra18": "Submit data request?",
  "uiExtra19": "Submit request",
  "uiExtra20": "A request is tracked for review. It does not immediately delete your account or financial history.",
  "uiExtra21": "Share device-only entries?",
  "uiExtra22": "Share reviewed copy",
  "uiExtra23": "This copy contains private financial data and original Pending or Needs attention requests. It is not proof of a server balance. Choose a trusted recipient. Keep this app data until all entries are resolved.",
  "uiExtra24": "Requests are reviewed. Historical financial records are retained until the approved privacy policy and operator process permit deletion. This test version does not perform destructive deletion.",
  "uiExtra25": "Request shop data export",
  "uiExtra26": "Request shop deletion",
  "uiExtra27": "Export device-only requests",
  "uiExtra28": "Request account deletion",
  "uiExtra29": "Refresh request status",
  "uiExtra30": "Request ID",
  "uiExtra31": "Remove my access to this shop",
  "uiExtra32": "Remove shop access?",
  "uiExtra33": "Remove access",
  "uiExtra34": "You will no longer see this shop ledger. The owner keeps the original financial history. Relinking is unavailable until the privacy policy is reviewed.",
  "uiExtra35": "export",
  "uiExtra36": "shop_deletion",
  "uiExtra37": "account_deletion",
  "uiExtra38": "access_removal",
  "uiExtra39": "requested",
  "uiExtra40": "under_review",
  "uiExtra41": "approved",
  "uiExtra42": "completed",
  "uiExtra43": "rejected",
  "uiExtra44": "failed",
  "uiExtra46": "Settings",
  "uiExtra47": "Pending",
  "uiExtra48": "Synced",
  "uiExtra50": "credit",
  "uiExtra51": "payment",
  "uiExtra52": "correction",
  "uiExtra53": "cash",
  "uiExtra54": "upi",
  "uiExtra55": "refresh",
  "sync.failed": "Sync could not be confirmed. Keep the saved entries and retry sync; do not re-enter them.",
  "sync.unavailable": "Sync is unavailable. Device Pending entries are retained; connect and retry later.",
  "sync.invalidResponse": "Sync response could not be verified. Keep device data and retry the same saved entries.",
  "sync.integrityError": "Ledger reconciliation failed. Keep app data and contact support before entering more transactions.",
  "api.tlsRequired": "A secure HTTPS connection is required.",
  "correction.invalid": "Use a valid corrected amount and reason. The original entry is retained.",
  "correction.pending":
      "Review the saved correction before creating another request.",
  "correction.revisionConflict": "This entry has a newer correction. Refresh and review its current amount.",
  "correction.balanceConflict": "This correction would make the balance invalid. Refresh and review the amount.",
  "dispute.invalid": "Enter a dispute reason of at most 500 characters.",
  "dispute.conflict":
      "The dispute status changed. Refresh before resolving it.",
  "uiFinal0": "Checking this QR online.",
  "uiFinal1": "Could not open your account",
  "uiFinal2": "Customer QR camera scanner",
  "uiFinal3": "My QR",
  "uiFinal4": "My shops",
  "uiFinal5": "Open your shop again to scan a customer.",
  "uiFinal6": "Opening account",
  "uiFinal7": "Opening your account",
  "uiFinal8": "Page unavailable",
  "uiFinal9": "Please wait.",
  "uiFinal10": "Refresh due summary",
  "uiFinal11": "Shop nickname",
  "uiFinal12": "This page could not be opened.",
  "final271": "Provisional, including Pending",
  "final272": "(provisional, including Pending).",
  "final273": "(last server read).",
  "final274": "Synced balance",
  "final275": "Last server snapshot",
  "final276": "Partial refresh",
  "final277": "Complete snapshot remains dated above.",
  "final278": "Created by shop owner",
  "final279": "Payment received",
  "final280": "Recorded",
  "final281": "Server snapshot",
  "final282": "Refresh for newer changes.",
  "final283": "Pending · Waiting to sync · Only on this device",
  "final284": "Credit",
  "final285": "Payment",
  "final286": "Entry date",
  "final287": "Due",
  "final288": "Method",
  "final289": "View disputes",
  "final290": "Raise or view dispute",
  "final291": "(server balance as of {time}).",
  "final292": "Shop nickname: {name}",
  "final293":
      "Balance when this payment was recorded: Customer owes you {amount}",
  "final294": "{method} received on this device: {amount}",
  "final295": "{method} received: {amount}",
  "final296": "Last verified: {time}",
  "final297": "Last sync: {time}",
  "final298": "{pending} Pending · {attention} Needs attention",
  "final299": "Entry date: {time}",
  "final300": "{count} pending entries will stay on this phone, locked to this account. They are not backed up to the cloud.",
  "final301": "Checking payment…",
  "final302": "Confirm payment received",
  "final303": "Check same payment",
  "final304": "Review the customer, amount and method before confirming. Saved entries are Pending and only on this device until synced. Payments cannot exceed the locally known balance.",
  "final305": "Internet is needed. Review the customer, amount and method before confirming payment received. The server checks the latest balance.",
  "final306": "Access is no longer available. Original entries are retained on this device.",
  "final307": "The balance changed. Review the confirmed ledger before recording another entry.",
  "final308": "This ledger is too large for offline entry. View confirmed server history online.",
  "final309": "Sync is unavailable on this server. Saved entries remain on this device.",
  "final310": "Please sign in again to continue syncing.",
  "final311": "Recover the earlier online attempt before syncing new entries.",
  "final312":
      "Offline. Saved entries will sync when a connection is available.",
  "final313": "Sync will retry after the server waiting period.",
  "final314":
      "Sync could not finish. Original entries are retained; try again later.",
  "final315": "Sync now",
  "final316": "Syncing…",
  "final317": "More requests exist. This list shows the latest 100.",
  "final318": "Your account role is fixed when you first register.",
  "final319": "Sign-in needs the approved Google configuration.",
  "final320": "Creating shop…",
  "final321": "Create shop",
  "final322": "Enter your shop name.",
  "final323": "Confirm your customer",
  "final324": "Internet needed to add customer",
  "final325": "The complete dispute list exceeds this device limit. No partial list is shown.",
  "final326": "Last successful sync",
  "final327": "Offline: newer owner changes may be missing.",
  "final328": "Total customers owe you",
  "final329": "customer ledgers, including retained ledgers.",
  "final330": "Confirmed",
  "final331": "Last server read",
  "final332": "The entry or dispute changed. Refresh and review the latest revision before trying again.",
  "api.revisionConflict": "The entry or dispute changed. Refresh and review the latest revision before trying again.",
  "final334": "Oldest Pending saved: {time}",
  "final335": "api.tlsRequired",
  "final336": "Balance when this credit was recorded: {balance}",
  "final337": "Credit amount: {amount}",
  "final338": "Credit recorded on this device: {amount}",
  "final339": "Credit recorded: {amount}",
  "final340": "Customer owes you {amount} more in the provisional balance after saving.",
  "final341":
      "Customer owes you {amount} more after this credit is acknowledged.",
  "final342": "Due date: {date}",
  "final343": "Note: {note}",
  "final344": "Clear due date",
  "final345": "Choose a valid date from the calendar.",
  "final346": "Use at most 500 characters.",
  "final347": "Confirm credit",
  "final348": "Check same credit",
  "final349": "Checking credit…",
  "final350": "Review the customer and amount before confirming. Saved entries are Pending and only on this device until synced.",
  "final351": "Internet is needed. Review the customer and amount before confirming. No credit is posted until confirmation.",
  "final352": "Enter a positive INR amount with at most two decimals.",
  "final353": "Use an amount from ₹0.01 to ₹1,00,000.00.",
  "final354": "Last checked",
  "final355": "QR replacement failed.",
  "final356": "Scan the customer’s Udhaar Khata QR. Known saved customers can open offline. Internet is needed to add a customer.",
  "final357": "Camera permission needed",
  "final358": "Camera unavailable",
  "final359": "Your customer account",
  "final360":
      "Saved QR — not checked online. It may have changed on another phone.",
  "final361": "QR checked online.",
  "final362": "Customer identification QR. Show this to the shopkeeper. It does not authorize a payment.",
  "final363": "Refresh QR",
  "final364": "Sign in again",
};
final Map<String, String> _hi = {
  "ui0": "रद्द करें",
  "ui1": "फिर कोशिश करें",
  "ui2": "ग्राहक",
  "ui3": "ग्राहक",
  "ui4": "दुकानदार",
  "ui5": "आपकी दुकान",
  "ui6": "अपनी दुकान बनाएं",
  "ui7": "दुकान का नाम",
  "ui8": "दुकान में ग्राहक का नाम (वैकल्पिक)",
  "ui9": "Google से जारी रखें",
  "ui10": "साइन आउट",
  "ui11": "साइन आउट करें?",
  "ui12": "बदलें",
  "ui13": "QR बदलें",
  "ui14": "अपना QR बदलें?",
  "ui15": "लेनदेन का इतिहास",
  "ui16": "लेनदेन का इतिहास देखें",
  "ui17": "क्लाउड में पुष्टि किया गया इतिहास देखें",
  "ui18": "सहेजा खाता देखें",
  "ui19": "ग्राहक का खाता",
  "ui20": "सहेजे ग्राहक खाते",
  "ui21": "उधार दर्ज करें",
  "ui22": "प्राप्त भुगतान दर्ज करें",
  "ui23": "राशि (₹)",
  "ui24": "प्राप्त राशि (₹)",
  "ui25": "टिप्पणी (वैकल्पिक)",
  "ui26": "भुगतान की तारीख (वैकल्पिक)",
  "ui27": "नकद",
  "ui28": "UPI",
  "ui29": "ग्राहक पर लौटें",
  "ui30": "खाते पर लौटें",
  "ui31": "बकाया ताज़ा करें",
  "ui32": "क्लाउड से ताज़ा करें",
  "ui33": "और दिखाएं",
  "ui34": "पन्ना फिर खोलें",
  "ui35": "अभी कोई लेनदेन नहीं है।",
  "ui36": "कृपया साइन इन करें",
  "ui37": "जारी रखने के लिए साइन इन करें।",
  "ui38": "साइन इन करके इस ग्राहक को फिर खोलें।",
  "ui39": "खाता खोलने के लिए साइन इन करें।",
  "ui40": "ग्राहक नहीं खुल पाया",
  "ui41": "आपकी दुकान नहीं खुल पाई",
  "ui42": "साइन आउट नहीं हुआ। फिर कोशिश करें।",
  "ui43": "ग्राहक का QR स्कैन करें",
  "ui44": "दूसरा QR स्कैन करें",
  "ui45": "रद्द करके फिर स्कैन करें",
  "ui46": "यह दुकानदार को दिखाएं",
  "ui47": "आपका QR जांच रहे हैं",
  "ui48": "पिछला अनुरोध जांच रहे हैं",
  "ui49": "ग्राहक खोज रहे हैं",
  "ui50": "ग्राहक खोल रहे हैं",
  "ui51": "दुकान खोल रहे हैं",
  "ui52": "क्लाउड रिकॉर्ड लोड हो रहे हैं",
  "ui53": "सहेजा खाता लोड हो रहा है",
  "ui54": "उधार फ़ॉर्म लोड हो रहा है",
  "ui55": "भुगतान फ़ॉर्म लोड हो रहा है",
  "ui56": "सेटिंग खोलें",
  "ui57": "कैमरा फिर चालू करें",
  "ui58": "विवाद",
  "ui59": "विवाद दर्ज करें",
  "ui60": "विवाद ताज़ा करें",
  "ui61": "कारण",
  "ui62": "प्राप्तकर्ता",
  "ui63": "नीचे टिप्पणी लिखकर समाधान करें",
  "ui64": "रिकॉर्ड सुधारें",
  "ui65": "सही राशि (₹, शून्य भी मान्य)",
  "ui66": "सुधार की पुष्टि करें",
  "ui67": "सुधार जांचें",
  "ui68": "सुधार बदलें",
  "ui69": "उधार बदलें",
  "ui70": "भुगतान बदलें",
  "ui71": "राशि और तरीका बदलें",
  "ui72": "उधार जांचें",
  "ui73": "भुगतान जांचें",
  "ui74": "सहेजा उधार जांचें",
  "ui75": "सहेजा भुगतान जांचें",
  "ui76": "सहेजा अनुरोध जांचें",
  "ui77": "उधार की क्लाउड में पुष्टि हुई",
  "ui78": "भुगतान की क्लाउड में पुष्टि हुई",
  "ui79": "उधार सहेजा · सिंक बाकी",
  "ui80": "भुगतान सहेजा · सिंक बाकी",
  "ui81": "भुगतान अस्वीकृत; कोई भुगतान दर्ज नहीं हुआ।",
  "ui82": "नया फ़ोन और खाता वापस पाना",
  "ui83": "ग्राहक के उधार का आसान हिसाब।",
  "ui84":
      "सिंक बाकी रिकॉर्ड केवल इस फ़ोन पर हैं; क्लाउड में सुरक्षित नहीं हैं।",
  "ui85":
      "सिंक बाकी रिकॉर्ड केवल इस फ़ोन पर हैं। क्लाउड में सुरक्षित नहीं हैं।",
  "ui86": "क्लाउड के कुल में केवल सिंक किए रिकॉर्ड हैं। सिंक बाकी रिकॉर्ड केवल इस फ़ोन पर हैं।",
  "ui87": "ऑफ़लाइन · इस फ़ोन पर सहेजे खाते की अनुमति",
  "ui88": "ऑफ़लाइन · सहेजी स्थिति · केवल पढ़ सकते हैं। नए बदलाव के लिए ऑनलाइन ताज़ा करें।",
  "ui89":
      "नकद/UPI आप स्वयं दर्ज करते हैं। ऐप बैंक हस्तांतरण की जांच नहीं करता।",
  "ui90":
      "नकद/UPI दुकानदार स्वयं दर्ज करते हैं; बैंक हस्तांतरण की जांच नहीं होती।",
  "ui91": "मूल रिकॉर्ड रहता है। सुधार उसकी प्रभावी राशि बदलता है।",
  "ui92": "विवाद बकाया नहीं बदलता। दुकानदार राशि का सुधार अलग दर्ज करते हैं।",
  "ui93": "यह QR आपका खाता पहचानता है। दुकानदार पहचान की पुष्टि करके राशि दर्ज करते हैं। यह भुगतान का QR नहीं है।",
  "ui94": "ग्राहक का Udhaar Khata QR स्कैन करें। ग्राहक पहचानने और जोड़ने के लिए इंटरनेट चाहिए।",
  "ui95": "ग्राहक का QR स्कैन करने के लिए कैमरे की अनुमति दें। Android सेटिंग में कैमरे की अनुमति बदल सकते हैं।",
  "ui96": "Android सेटिंग में ऐप, Udhaar Khata, अनुमतियां खोलकर कैमरे की अनुमति दें।",
  "ui97": "इस फ़ोन पर सहेजा है। बकाया में सिंक बाकी रिकॉर्ड हो सकते हैं।",
  "ui98": "क्लाउड की पिछली स्थिति दिखाई गई है। नया पन्ना सत्यापित नहीं हुआ।",
  "ui99": "मूल रिकॉर्ड सुरक्षित है। नया रिकॉर्ड दर्ज करने से पहले उसे जांचें।",
  "ui100": "पिछले रिकॉर्ड के कारण रुका है। पहले मूल रिकॉर्ड जांचें।",
  "ui101": "नया बकाया देखने के लिए ग्राहक का खाता ताज़ा करें।",
  "ui102": "उधार खाता",
  "ui103": "DD-MM-YYYY",
  "ui104": "सिंक बाकी रिकॉर्ड केवल इस फ़ोन पर हैं, क्लाउड में सुरक्षित नहीं। ग्राहक को केवल क्लाउड में पुष्टि किए रिकॉर्ड दिखते हैं।",
  "ui105": "फ़ोन बदलने से पहले पुराने फ़ोन को इंटरनेट से जोड़कर सिंक करें। कोई रिकॉर्ड सिंक बाकी या जांच ज़रूरी न रहे। पुष्टि किया इतिहास जांचे बिना अनिश्चित रिकॉर्ड दोबारा न दर्ज करें।",
  "ui106": "सिंक बाकी रिकॉर्ड केवल उस फ़ोन पर हैं। सिंक से पहले फ़ोन खोने, खराब होने या ऐप डेटा मिटने पर क्लाउड से वे रिकॉर्ड वापस नहीं मिलेंगे।",
  "ui107": "नए फ़ोन पर इंटरनेट से जुड़कर उसी Google खाते से साइन इन करें। खाते खोलकर क्लाउड में पुष्टि किए रिकॉर्ड डाउनलोड करें।",
  "ui108": "ऑफ़लाइन ग्राहक को क्लाउड की पिछली स्थिति दिखती है। इंटरनेट से जुड़कर ताज़ा करने तक दुकानदार के नए बदलाव नहीं दिख सकते।",
  "ui109": "सहेजे उधार की पुष्टि नहीं हुई। यह क्लाउड पर पहुंच चुका हो सकता है। उसी उधार को जांचें; दोबारा दर्ज न करें।",
  "ui110": "सहेजे भुगतान की पुष्टि नहीं हुई। यह क्लाउड पर पहुंच चुका हो सकता है। उसी भुगतान को जांचें; दोबारा दर्ज न करें।",
  "ui111": "क्लाउड का बकाया बदल गया है। नया रिकॉर्ड दर्ज करने से पहले सिंक बाकी रिकॉर्ड जांचें।",
  "ui112": "सुधार सहेजा · सिंक बाकी · केवल इस फ़ोन पर। सिंक होने तक क्लाउड में सुरक्षित नहीं है।",
  "ui113": "एक सुधार सिंक बाकी या जांच ज़रूरी है। पुष्टि की गई प्रभावी राशि में यह शामिल नहीं है।",
  "ui114": "क्लाउड में पुष्टि किए रिकॉर्ड। दुकानदार भुगतान स्वयं दर्ज करते हैं; बैंक हस्तांतरण जांचा नहीं जाता।",
  "ui115": "सहेजी राशि बकाया से अधिक है या खाते की सीमा पूरी हुई है। वर्तमान बकाया जांचकर स्वयं राशि सुधारें।",
  "ui116": "ग्राहक दुकान से जुड़ गया है। स्कैन करके ग्राहक जोड़ने से उधार या भुगतान दर्ज नहीं होता।",
  "ui117": "इंटरनेट चाहिए। पुराना QR नई दुकान जोड़ने के लिए बंद होगा। मौजूदा दुकान के खाते बने रहेंगे।",
  "ui118": "QR जांचने या बदलने के लिए फिर साइन इन करें। सहेजा कोड ऑनलाइन सत्यापित नहीं हुआ है।",
  "ui119":
      "इस फ़ोन से साइन आउट हो गया। क्लाउड सत्र समाप्त होने की पुष्टि नहीं हुई।",
  "ui120": "ग्राहक अपने खाते के पास यह नाम देखेंगे। इस संस्करण में एक दुकानदार की एक दुकान है। बनाने के लिए इंटरनेट चाहिए।",
  "statement.title": "विवरण और याद दिलाना",
  "statement.from": "शुरुआत की तारीख (UTC)",
  "statement.to": "अंत की तारीख (UTC)",
  "statement.load": "पूर्वावलोकन बनाएं",
  "statement.bounds": "अधिकतम 366 दिन चुनें। अधिकतम 5,000 पुष्टि किए रिकॉर्ड निर्यात कर सकते हैं।",
  "statement.period": "UTC में दर्ज अवधि: {from} से {to}",
  "statement.sensitive": "निजी वित्तीय जानकारी। ग्राहक जांचें और शेयर मेनू में सही प्राप्तकर्ता चुनें। सिंक बाकी रिकॉर्ड शामिल नहीं हैं।",
  "statement.opening": "शुरुआती बकाया: {amount}",
  "statement.closing": "अंतिम बकाया: {amount}",
  "statement.shareCsv": "CSV शेयर करें",
  "statement.sharePdf": "PDF शेयर करें",
  "reminder.share": "जांचा संदेश शेयर करें",
  "reminder.label": "याद दिलाने का संदेश (बदल सकते हैं)",
  "reminder.template": "नमस्ते {customer}, {shop} के पुष्टि किए रिकॉर्ड के अनुसार {asOf} तक आपका बकाया {amount} है। कृपया अपना खाता जांचें। नए या सिंक बाकी रिकॉर्ड शामिल नहीं हो सकते हैं। धन्यवाद।",
  "owner.owes": "ग्राहक को आपको {amount} देना है",
  "customer.owes": "आपको {shop} को {amount} देना है",
  "language": "भाषा",
  "help": "सहायता और खाता वापस पाना",
  "sync.pending": "सिंक बाकी · केवल इस फ़ोन पर",
  "sync.synced": "सिंक हुआ · क्लाउड में पुष्टि हुई",
  "sync.attention": "जाँच ज़रूरी",
  "error.generic": "यह काम पूरा नहीं हुआ। फिर कोशिश करें।",
  "ledger.cacheTooLarge":
      "यह खाता ऑफ़लाइन सहेजने के लिए बड़ा है। ऑनलाइन पुष्टि किया इतिहास देखें।",
  "ledger.localOverpayment":
      "भुगतान सहेजे बकाया से अधिक है। सहेजने से पहले राशि जांचें।",
  "ledger.cacheRequired": "ऑफ़लाइन रिकॉर्ड दर्ज करने से पहले इस ग्राहक को ऑनलाइन खोलकर खाता सत्यापित और सहेजें।",
  "api.cursorInvalid":
      "यह स्थिति पुरानी हो गई है। नए रिकॉर्ड के लिए ताज़ा करें।",
  "history.invalidResponse":
      "क्लाउड रिकॉर्ड सत्यापित नहीं हुए। ताज़ा करके फिर कोशिश करें।",
  "history.failed": "रिकॉर्ड नहीं खुले। इंटरनेट जांचकर फिर कोशिश करें।",
  "api.capacityUnavailable":
      "क्लाउड अभी कुल नहीं दे सकता। बाद में फिर कोशिश करें।",
  "payment.pending":
      "इस ग्राहक का नया उधार या भुगतान दर्ज करने से पहले सहेजा भुगतान जांचें।",
  "payment.creditPending": "भुगतान दर्ज करने से पहले सहेजा उधार जांचें।",
  "payment.savedInvalid": "सहेजा भुगतान नहीं पढ़ा गया। ऐप डेटा सुरक्षित रखें और दोबारा दर्ज करने से पहले सहायता लें।",
  "payment.invalid": "₹1,00,000 तक सकारात्मक राशि और नकद या UPI चुनें।",
  "payment.balanceConflict": "भुगतान बकाया या खाते की सीमा से अधिक होने पर अस्वीकृत हुआ। बकाया ताज़ा करके राशि जांचें।",
  "payment.failed": "भुगतान सत्यापित नहीं हुआ। उसी सहेजे अनुरोध को जांचें; दोबारा दर्ज न करें।",
  "credit.pending":
      "इस ग्राहक का नया उधार दर्ज करने से पहले सहेजा उधार जांचें।",
  "credit.savedInvalid": "सहेजा उधार नहीं पढ़ा गया। ऐप डेटा सुरक्षित रखें और दोबारा दर्ज करने से पहले सहायता लें।",
  "credit.invalid":
      "₹1,00,000 तक सकारात्मक राशि, 500 अक्षर तक टिप्पणी और मान्य तारीख दें।",
  "credit.clockInvalid":
      "फ़ोन की तारीख और समय जांचें। अनुरोध जांच के लिए सहेजा है।",
  "credit.balanceLimit":
      "उधार खाते की समर्थित सीमा से अधिक है। सहेजा अनुरोध जांचना ज़रूरी है।",
  "credit.failed":
      "उधार सत्यापित नहीं हुआ। उसी सहेजे अनुरोध को जांचें; दोबारा दर्ज न करें।",
  "link.internetNeeded":
      "ग्राहक पहचानने और जोड़ने के लिए इंटरनेट चाहिए। जुड़कर फिर कोशिश करें।",
  "qr.invalid": "यह मान्य Udhaar Khata ग्राहक QR नहीं है।",
  "qr.unsupported": "इस QR संस्करण का समर्थन नहीं है। नया ग्राहक QR मांगें।",
  "qr.revoked": "यह QR सक्रिय नहीं है। ग्राहक का नया QR मांगें।",
  "api.notFound": "यह दुकान या ग्राहक अब आपके खाते में उपलब्ध नहीं है।",
  "api.idempotencyConflict": "यह अनुरोध पहले की पुष्टि से अलग है। उसी सहेजे अनुरोध को जांचें; नया लेनदेन न बनाएं।",
  "api.invalidResponse": "उत्तर सत्यापित नहीं हुआ। उसी अनुरोध को फिर जांचें।",
  "link.pending": "दूसरा QR स्कैन करने से पहले पिछले ग्राहक की पुष्टि जांचें।",
  "link.savedRequestInvalid":
      "सहेजी पुष्टि नहीं पढ़ी गई। नया ग्राहक जोड़ने से पहले सहायता लें।",
  "link.nicknameInvalid": "दुकान में ग्राहक का नाम 120 अक्षर तक रखें।",
  "link.failed": "ग्राहक की पुष्टि नहीं हुई। इंटरनेट जांचकर फिर कोशिश करें।",
  "auth.required": "जारी रखने के लिए साइन इन करें।",
  "auth.forbidden": "इस पन्ने की अनुमति आपके खाते को नहीं है।",
  "auth.cancelled": "साइन इन रद्द हुआ। फिर कोशिश कर सकते हैं।",
  "auth.identityInvalid":
      "Google साइन इन समाप्त या सत्यापित नहीं हुआ। फिर साइन इन करें।",
  "auth.roleConflict":
      "इस Google खाते की भूमिका अलग है। उसकी मूल भूमिका चुनें।",
  "api.rateLimited": "बहुत बार कोशिश हुई। थोड़ी देर बाद फिर कोशिश करें।",
  "api.networkError": "कनेक्शन नहीं हुआ। इंटरनेट जांचकर फिर कोशिश करें।",
  "qr.recoveryRequired": "इंटरनेट से जुड़कर QR ताज़ा करें। बदलने की पुष्टि नहीं हुई, इसलिए सहेजा QR छिपा है।",
  "api.featureUnavailable": "यह सुविधा अभी उपलब्ध नहीं है। बाद में कोशिश करें।",
  "qr.rotationRecovered":
      "बदलने का उत्तर सत्यापित नहीं हुआ। क्लाउड का नवीनतम QR दिख रहा है।",
  "api.validationError": "फ़ॉर्म की जानकारी जांचकर फिर कोशिश करें।",
  "api.internalError":
      "क्लाउड अनुरोध पूरा नहीं कर पाया। उसी सहेजे अनुरोध को फिर जांचें।",
  "api.methodNotAllowed": "यह कार्रवाई समर्थित नहीं है।",
  "api.invalidJson": "सहेजा अनुरोध नहीं पढ़ा गया। सहायता लें।",
  "api.jsonRequired": "अनुरोध का प्रारूप समर्थित नहीं है।",
  "api.payloadTooLarge": "अनुरोध बहुत बड़ा है। जानकारी कम करें।",
  "shop.closed": "यह दुकान बंद है।",
  "correction.failed": "सुधार सत्यापित नहीं हुआ। उसी सहेजे अनुरोध को जांचें।",
  "dispute.failed": "विवाद सत्यापित नहीं हुआ। ताज़ा करके फिर कोशिश करें।",
  "uiExtra0": "मूल राशि",
  "uiExtra1": "पुष्टि की गई प्रभावी राशि",
  "uiExtra2": "सुधार",
  "uiExtra3": "वर्तमान पुष्टि की गई राशि",
  "uiExtra4": "मूल रिकॉर्ड",
  "uiExtra5": "सही की गई राशि",
  "uiExtra6": "बकाया",
  "uiExtra7": "तारीख बीत चुकी बकाया राशि",
  "uiExtra8": "क्लाउड में पुष्टि किया सारांश",
  "uiExtra9": "बनाया गया",
  "uiExtra10": "समाधान",
  "uiExtra11": "खुला",
  "uiExtra12": "हल हुआ",
  "uiExtra13": "रिकॉर्ड",
  "uiExtra14": "विवाद का कारण",
  "uiExtra15": "समाधान की टिप्पणी",
  "uiExtra16": "सेटिंग और डेटा नियंत्रण",
  "uiExtra17": "डेटा अनुरोध",
  "uiExtra18": "डेटा अनुरोध भेजें?",
  "uiExtra19": "अनुरोध भेजें",
  "uiExtra20": "अनुरोध समीक्षा के लिए दर्ज होता है। इससे आपका खाता या वित्तीय इतिहास तुरंत नहीं मिटता।",
  "uiExtra21": "केवल फ़ोन पर सहेजे रिकॉर्ड शेयर करें?",
  "uiExtra22": "जांची कॉपी शेयर करें",
  "uiExtra23": "इस कॉपी में निजी वित्तीय डेटा और मूल सिंक बाकी या जांच ज़रूरी अनुरोध हैं। यह क्लाउड के बकाया का प्रमाण नहीं है। विश्वसनीय प्राप्तकर्ता चुनें। सभी रिकॉर्ड हल होने तक ऐप डेटा सुरक्षित रखें।",
  "uiExtra24": "अनुरोध की समीक्षा होती है। स्वीकृत गोपनीयता नीति और संचालक प्रक्रिया की अनुमति तक पुराने वित्तीय रिकॉर्ड सुरक्षित रहते हैं। यह परीक्षण संस्करण डेटा मिटाता नहीं है।",
  "uiExtra25": "दुकान का डेटा निर्यात मांगें",
  "uiExtra26": "दुकान मिटाने का अनुरोध करें",
  "uiExtra27": "केवल फ़ोन पर सहेजे अनुरोध निर्यात करें",
  "uiExtra28": "खाता मिटाने का अनुरोध करें",
  "uiExtra29": "अनुरोध की स्थिति ताज़ा करें",
  "uiExtra30": "अनुरोध आईडी",
  "uiExtra31": "इस दुकान में मेरी पहुंच हटाएं",
  "uiExtra32": "दुकान में पहुंच हटाएं?",
  "uiExtra33": "पहुंच हटाएं",
  "uiExtra34": "आप इस दुकान का खाता नहीं देख पाएंगे। मूल वित्तीय इतिहास दुकानदार के पास रहेगा। गोपनीयता नीति की समीक्षा तक फिर जोड़ना उपलब्ध नहीं है।",
  "uiExtra35": "डेटा निर्यात",
  "uiExtra36": "दुकान मिटाने का अनुरोध",
  "uiExtra37": "खाता मिटाने का अनुरोध",
  "uiExtra38": "पहुंच हटाना",
  "uiExtra39": "अनुरोध दर्ज",
  "uiExtra40": "समीक्षा चल रही है",
  "uiExtra41": "स्वीकृत",
  "uiExtra42": "पूरा हुआ",
  "uiExtra43": "अस्वीकृत",
  "uiExtra44": "विफल",
  "uiExtra46": "सेटिंग",
  "uiExtra47": "सिंक का इंतज़ार",
  "uiExtra48": "सर्वर से पुष्ट",
  "uiExtra50": "उधार",
  "uiExtra51": "भुगतान",
  "uiExtra52": "सुधार",
  "uiExtra53": "नकद",
  "uiExtra54": "UPI",
  "uiExtra55": "ताज़ा करें",
  "sync.failed": "सिंक की पुष्टि नहीं हुई। सहेजे रिकॉर्ड रखें और फिर सिंक करें; दोबारा दर्ज न करें।",
  "sync.unavailable": "सिंक अभी उपलब्ध नहीं है। सिंक बाकी रिकॉर्ड इस फ़ोन पर सुरक्षित हैं; इंटरनेट से जुड़कर बाद में फिर कोशिश करें।",
  "sync.invalidResponse": "सिंक का उत्तर सत्यापित नहीं हुआ। फ़ोन का डेटा रखें और उन्हीं सहेजे रिकॉर्ड को फिर सिंक करें।",
  "sync.integrityError": "खाते का मिलान नहीं हुआ। ऐप डेटा रखें और नया लेनदेन दर्ज करने से पहले सहायता लें।",
  "api.tlsRequired": "सुरक्षित HTTPS कनेक्शन ज़रूरी है।",
  "correction.invalid": "सही राशि और कारण दें। मूल रिकॉर्ड सुरक्षित रहता है।",
  "correction.pending": "नया अनुरोध बनाने से पहले सहेजा सुधार जांचें।",
  "correction.revisionConflict":
      "इस रिकॉर्ड में नया सुधार है। ताज़ा करके वर्तमान राशि जांचें।",
  "correction.balanceConflict":
      "इस सुधार से बकाया अमान्य होगा। ताज़ा करके राशि जांचें।",
  "dispute.invalid": "विवाद का कारण अधिकतम 500 अक्षर में लिखें।",
  "dispute.conflict": "विवाद की स्थिति बदली है। समाधान से पहले ताज़ा करें।",
  "uiFinal0": "QR की ऑनलाइन जांच हो रही है।",
  "uiFinal1": "आपका खाता नहीं खुल पाया",
  "uiFinal2": "ग्राहक QR के लिए कैमरा स्कैनर",
  "uiFinal3": "मेरा QR",
  "uiFinal4": "मेरी दुकानें",
  "uiFinal5": "ग्राहक स्कैन करने के लिए अपनी दुकान फिर खोलें।",
  "uiFinal6": "खाता खुल रहा है",
  "uiFinal7": "आपका खाता खुल रहा है",
  "uiFinal8": "पन्ना उपलब्ध नहीं है",
  "uiFinal9": "कृपया प्रतीक्षा करें।",
  "uiFinal10": "भुगतान तारीख का सारांश ताज़ा करें",
  "uiFinal11": "दुकान में ग्राहक का नाम",
  "uiFinal12": "यह पन्ना नहीं खुल पाया।",
  "final271": "अस्थायी कुल, सिंक का इंतज़ार कर रही प्रविष्टियों सहित",
  "final272": "(अस्थायी कुल, सिंक का इंतज़ार कर रही प्रविष्टियों सहित)।",
  "final273": "(सर्वर से पिछली जानकारी)।",
  "final274": "सर्वर से पुष्ट बकाया",
  "final275": "सर्वर की पिछली पुष्ट जानकारी",
  "final276": "अधूरी नई जानकारी",
  "final277": "पूरी पुष्ट जानकारी ऊपर दी गई तारीख की है।",
  "final278": "दुकान के मालिक ने दर्ज किया",
  "final279": "भुगतान प्राप्त हुआ",
  "final280": "दर्ज किया",
  "final281": "सर्वर की पुष्ट जानकारी",
  "final282": "नई जानकारी के लिए रीफ़्रेश करें।",
  "final283": "सिंक का इंतज़ार · केवल इस फ़ोन पर",
  "final284": "उधार",
  "final285": "भुगतान",
  "final286": "प्रविष्टि की तारीख",
  "final287": "देय तारीख",
  "final288": "भुगतान का तरीका",
  "final289": "विवाद देखें",
  "final290": "विवाद दर्ज करें या देखें",
  "final291": "(सर्वर का बकाया {time} तक)।",
  "final292": "दुकान में ग्राहक का नाम: {name}",
  "final293": "भुगतान दर्ज करते समय ग्राहक को आपको {amount} देना था",
  "final294": "इस फ़ोन पर दर्ज प्राप्त {method} भुगतान: {amount}",
  "final295": "प्राप्त {method} भुगतान: {amount}",
  "final296": "अंतिम सत्यापन: {time}",
  "final297": "अंतिम सिंक: {time}",
  "final298": "{pending} सिंक का इंतज़ार · {attention} जाँच ज़रूरी",
  "final299": "प्रविष्टि की तारीख: {time}",
  "final300": "सिंक का इंतज़ार कर रही {count} प्रविष्टियाँ इसी फ़ोन पर इस खाते में सुरक्षित रहेंगी। इनका क्लाउड बैकअप नहीं है।",
  "final301": "भुगतान की जाँच हो रही है…",
  "final302": "प्राप्त भुगतान की पुष्टि करें",
  "final303": "इसी सहेजे भुगतान की जाँच करें",
  "final304": "पुष्टि से पहले ग्राहक, रकम और भुगतान का तरीका जाँचें। सिंक होने तक सहेजी प्रविष्टियाँ केवल इसी फ़ोन पर हैं। भुगतान इस फ़ोन पर ज्ञात बकाये से अधिक नहीं हो सकता।",
  "final305": "इंटरनेट ज़रूरी है। प्राप्त भुगतान की पुष्टि से पहले ग्राहक, रकम और तरीका जाँचें। सर्वर नवीनतम बकाया जाँचता है।",
  "final306": "अब इस खाते को पहुँच की अनुमति नहीं है। मूल प्रविष्टियाँ इसी फ़ोन पर बनी रहेंगी।",
  "final307": "बकाया या प्रविष्टि का संशोधन बदल गया है। नई प्रविष्टि से पहले पुष्ट खाता जाँचें।",
  "final308": "यह खाता ऑफ़लाइन प्रविष्टियों के लिए बहुत बड़ा है। इंटरनेट से सर्वर का पुष्ट इतिहास देखें।",
  "final309":
      "इस सर्वर पर सिंक उपलब्ध नहीं है। सहेजी प्रविष्टियाँ इसी फ़ोन पर रहेंगी।",
  "final310": "सिंक जारी रखने के लिए फिर साइन इन करें।",
  "final311": "नई प्रविष्टियाँ सिंक करने से पहले पिछली अनिश्चित ऑनलाइन प्रविष्टि की जाँच करें।",
  "final312":
      "इंटरनेट नहीं है। कनेक्शन मिलने पर सहेजी प्रविष्टियाँ सिंक होंगी।",
  "final313": "सर्वर के बताए इंतज़ार के बाद सिंक फिर कोशिश करेगा।",
  "final314": "सिंक पूरा नहीं हुआ। मूल प्रविष्टियाँ बनी रहेंगी; बाद में फिर कोशिश करें।",
  "final315": "अभी सिंक करें",
  "final316": "सिंक हो रहा है…",
  "final317": "और अनुरोध मौजूद हैं। यहाँ नवीनतम 100 अनुरोध दिखाए गए हैं।",
  "final318": "पहली बार पंजीकरण के समय खाते की भूमिका तय होती है।",
  "final319": "साइन इन के लिए Google का सही कॉन्फ़िगरेशन चाहिए।",
  "final320": "दुकान बनाई जा रही है…",
  "final321": "दुकान बनाएँ",
  "final322": "अपनी दुकान का नाम लिखें।",
  "final323": "ग्राहक की पुष्टि करें",
  "final324": "ग्राहक जोड़ने के लिए इंटरनेट ज़रूरी है",
  "final325":
      "पूरी विवाद सूची इस फ़ोन की सीमा से बड़ी है। अधूरी सूची नहीं दिखाई जाती।",
  "final326": "अंतिम सफल सिंक",
  "final327": "इंटरनेट नहीं है: मालिक की नई प्रविष्टियाँ शामिल न हों।",
  "final328": "सभी ग्राहकों से कुल बकाया",
  "final329": "ग्राहक खाते, सुरक्षित रखे गए पुराने खातों सहित।",
  "final330": "पुष्ट",
  "final331": "सर्वर से पिछली जानकारी",
  "final332": "प्रविष्टि या विवाद बदल गया है। दोबारा कोशिश से पहले नवीनतम संशोधन रीफ़्रेश करके जाँचें।",
  "api.revisionConflict": "प्रविष्टि या विवाद बदल गया है। दोबारा कोशिश से पहले नवीनतम संशोधन रीफ़्रेश करके जाँचें।",
  "final334": "सबसे पुरानी सिंक का इंतज़ार कर रही प्रविष्टि: {time}",
  "final335": "TLS के साथ सुरक्षित कनेक्शन ज़रूरी है।",
  "final336": "यह उधार दर्ज होने के समय बकाया: {balance}",
  "final337": "उधार की राशि: {amount}",
  "final338": "इस फ़ोन पर दर्ज उधार: {amount}",
  "final339": "दर्ज उधार: {amount}",
  "final340":
      "सहेजने के बाद अस्थायी बकाया में ग्राहक को आपको {amount} और देना है।",
  "final341": "इस उधार की पुष्टि के बाद ग्राहक को आपको {amount} और देना है।",
  "final342": "देय तारीख: {date}",
  "final343": "टिप्पणी: {note}",
  "final344": "देय तारीख हटाएँ",
  "final345": "कैलेंडर से मान्य तारीख चुनें।",
  "final346": "अधिकतम 500 अक्षर लिखें।",
  "final347": "उधार की पुष्टि करें",
  "final348": "इसी उधार की जाँच करें",
  "final349": "उधार की जाँच हो रही है…",
  "final350": "पुष्टि से पहले ग्राहक और राशि जाँचें। सहेजी प्रविष्टियाँ सिंक होने तक केवल इसी फ़ोन पर हैं।",
  "final351": "इंटरनेट ज़रूरी है। पुष्टि से पहले ग्राहक और राशि जाँचें। पुष्टि तक उधार दर्ज नहीं होता।",
  "final352": "दो दशमलव तक सकारात्मक रुपये की राशि लिखें।",
  "final353": "₹0.01 से ₹1,00,000.00 तक राशि लिखें।",
  "final354": "अंतिम जाँच",
  "final355": "QR बदलना पूरा नहीं हुआ।",
  "final356": "ग्राहक का Udhaar Khata QR स्कैन करें। पहले से सत्यापित और सहेजे ग्राहक ऑफ़लाइन खुल सकते हैं। नया ग्राहक जोड़ने के लिए इंटरनेट ज़रूरी है।",
  "final357": "कैमरे की अनुमति ज़रूरी है",
  "final358": "कैमरा उपलब्ध नहीं है",
  "final359": "आपका ग्राहक खाता",
  "final360": "सहेजे QR की ऑनलाइन जाँच नहीं हुई है। यह दूसरे फ़ोन पर बदल चुका हो सकता है।",
  "final361": "QR की ऑनलाइन जाँच हो गई है।",
  "final362": "ग्राहक की पहचान का QR। इसे दुकानदार को दिखाएँ। इससे भुगतान की अनुमति नहीं मिलती।",
  "final363": "QR रीफ़्रेश करें",
  "final364": "फिर साइन इन करें",
};
